"""empty message

Revision ID: 13e71a362591
Revises: c3e866a55637
Create Date: 2021-12-01 14:02:45.867791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e71a362591'
down_revision = 'c3e866a55637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('friend_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customer', 'customer', ['friend_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'friend_id')
    # ### end Alembic commands ###
